[package]
name = "pixelvim"
version = "0.1.0"
edition = "2021"

[features]
default = ["lua"]
lua = ["dep:mlua"]

[dependencies]
miniquad = { path = "miniquad" }
nanoserde = { path = "nanoserde", default-features = false, features = ["std", "binary"] }
color_quant = "*"
png = "*"
gif = "*"
pico-args = "*"
snap = "*"
asefile = "*"
dirs = "*"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
mlua = { version = "*", default-features = false, features = ["lua51", "send", "vendored"], optional = true }

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[profile.release]
opt-level = 3       # Optimize for size
lto = true          # Enable link-time optimization
codegen-units = 1   # Reduce number of codegen units to increase optimizations
panic = 'abort'     # Abort on panic
strip = true        # Strip symbols from binary*
