map  j            down
map  k            up
map  h            left
map  l            right

map  esc          cancel THEN :select/clear
map  C-a          :select/all
map  C-i          :select/invert
map  C-k          :crop

map  C-r          :redo
map  u            :undo

map  y            :yank
map  p            :paste
map  d            :cut
map  x            :cut
map  delete       :delete
map  backspace    :delete

map/normal  -     normal_toggle
map/visual  -     visual_toggle

map/normal  e     normal_toggle THEN brush
map/visual  e     visual_toggle
map/normal  b     normal_blend THEN brush
map/normal  S-b   brush_filled
map/visual  b     brush_filled
map/visual  S-b   brush
map  f            flood_toggle
map  r            rect_toggle
map  c            ellipse_toggle
map  s            line
map  m            normal_blend THEN move
map  S-m          visual THEN move

map  tab          :toggle palette
map  alt          :set picker KEYUP :unset picker

map  S-j          :layer/go/below
map  S-k          :layer/go/above
map  S-h          :frame/go/left
map  S-l          :frame/go/right
map  o            :layer/new/below
map  S-o          :layer/new/above
map  S-d          :layer/delete
map  g            go
map  t            tab_front
map  S-t          tab_back
map  z            fit

map  ':'          command
map/normal  v     visual
map/visual  v     normal
map/visual  esc   cancel THEN normal THEN :select/clear

map  q            pixel_perfect
map  space        :toggle animation
map  enter        :frame/new/right
map  a            :toggle animation/edit/all
map  S-s          :slice
map  i            insert

-- mappings that might be useful
-- disabled by default
-- uncommment to activate

-- map  down         down
-- map  up           up
-- map  left         left
-- map  right        right

-- map  C-y          :redo
-- map  C-z          :undo

-- map  w            visual THEN flood
-- map  m            visual THEN rect_filled
-- map  F1           :set animation/speed=0.2
-- map  F2           :set animation/speed=1
-- map  F11          :toggle fullscreen
-- map  S-q          :quantize THEN :palette/build THEN :reduce

palette/clear
-- ENDESGA EDG32
#be4a2f
#d77643
#ead4aa
#e4a672
#b86f50
#733e39
#3e2731
#a22633
#e43b44
#f77622
#feae34
#fee761
#63c74d
#3e8948
#265c42
#193c3e
#124e89
#0099db
#2ce8f5
#ffffff
#c0cbdc
#8b9bb4
#5a6988
#3a4466
#262b44
#181425
#ff0044
#68386c
#b55088
#f6757a
#e8b796
#c28569
